services:
  mysql:
    image: mysql:8.4
    container_name: oficina-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oficina_db
      MYSQL_USER: oficina
      MYSQL_PASSWORD: oficina123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --lower_case_table_names=1
  adminer:
    image: adminer:4
    container_name: oficina-adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_data:
