services:

  mysql:
    image: mysql:8.4
    container_name: oficina-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oficina_db
      MYSQL_USER: oficina
      MYSQL_PASSWORD: oficina123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --lower_case_table_names=1

  phpmyadmin:
    image: phpmyadmin
    container_name: oficina-phpadmin
    restart: always
    ports:
      - 5050:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data:
